apiVersion: apps/v1
kind: Deployment
metadata:
  name:  jenkins
  namespace: default
  labels:
    app:  jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  jenkins
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  jenkins
        image:  bitnami/jenkins:latest
        env:
          - name: JENKINS_USERNAME
            value: test
        ports:
        - name:  http
          port:  8080   
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
