apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ printf "%s-%s" .Release.Name .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app:  jenkins
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  jenkins
        image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
        env:
          - name: JENKINS_USERNAME
            value: {{ default "test" .Values.jenkinsUsername | quote }}
          #helm control structure  
          - name: JENKINS_PASSWORD
            {{- if .Values.jenkinsPassword }}
            value: {{ .Values.jenkinsUsername }} 
            {{- else }} 
            value: testPassword 
            {{- end }}         
        ports:
          {{- range .Values.containerPorts }}
          - name: {{ .name }}
            containerPort: {{ .port }}
          {{- end }}    

